# Pokemon.csv column names
ID = 'ID'
NAME = 'Name'
TYPE_1 = 'Type_1'
TYPE_2 = 'Type_2'
TOTAL = 'Total'
HP = 'HP'
ATTACK = 'Attack'
DEFENSE = 'Defense'
SP_ATTACK = 'Sp_Atk'
SP_DEFENSE = 'Sp_Def'
SPEED = 'Speed'
GENERATION = 'Generation'
LEGENDARY = 'Legendary'
